### ISSUE TITLE
Stylesheet: Code tags should not have their case changed

### ISSUE THREAD

**Issue by wismill** [Nuclear-Squid/ergol#102]
In `www/assets/css/theme.css` the following lines are inconsistent and make _every_ `<code>` tags lowercase.

```css
code { /* character, digrams, trigrams */
  text-transform: uppercase;
  text-transform: lowercase;
}
```

I am contributing to the glossary and this make my examples invalid. You should use a dedicated CSS class (e.g. `.ngram`) where case transformation is necessary.
